apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  url: oci://quay.io/cilium/charts/cilium
  ref:
    digest: sha256:557ea3b67b2380bdf91f3006ecea924e10e2963dbaf6085887652311e581460b
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token.actions.githubusercontent.com$
        subject: ^https://github.com/cilium/cilium/.*$
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
