apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: cilium-values
    namespace: kube-system
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: cilium
    reconcile.fluxcd.io/watch: Enabled
