name: Validate GitOps configuration

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@c0c8b32d33a5244f1e5947304550403b63930415 # v4
        with:
          version: v1.36.2

      - name: Set up Helm
        uses: azure/setup-helm@bf6a7d304bc2fdb57e0331155b7ebf2c504acf0a # v4
        with:
          version: v4.2.2

      - name: Validate
        run: ./scripts/check.sh
